import { Question, Section } from "@/types/kiosk-interview";

// ============================================================================
// Section 1: Patient Demographic Information (Page 1) - ~26 questions
// ============================================================================

const section1Questions: Question[] = [
  {
    id: "demographics_firstName",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 0,
    labelEn: "What is your first name?",
    labelEs: "¿Cuál es su primer nombre?",
    helperTextEn: "Example: Maria",
    helperTextEs: "Ejemplo: María",
    inputType: "text",
    icon: "signature",
    required: true,
    fieldPath: "demographics.firstName",
    validation: { minLength: 1, maxLength: 50 },
  },
  {
    id: "demographics_lastName",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 1,
    labelEn: "What is your last name?",
    labelEs: "¿Cuál es su apellido?",
    helperTextEn: "Example: Garcia",
    helperTextEs: "Ejemplo: García",
    inputType: "text",
    icon: "signature",
    required: true,
    fieldPath: "demographics.lastName",
    validation: { minLength: 1, maxLength: 50 },
  },
  {
    id: "demographics_dateOfBirth",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 2,
    labelEn: "What is your date of birth?",
    labelEs: "¿Cuál es su fecha de nacimiento?",
    helperTextEn: "Month / Day / Year",
    helperTextEs: "Mes / Día / Año",
    inputType: "date",
    icon: "calendar",
    required: true,
    fieldPath: "demographics.dateOfBirth",
  },
  {
    id: "demographics_gender",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 3,
    labelEn: "What is your gender?",
    labelEs: "¿Cuál es su género?",
    inputType: "single_select",
    icon: "user",
    required: true,
    fieldPath: "demographics.gender",
    options: [
      { value: "male", labelEn: "Male", labelEs: "Masculino", icon: "male" },
      { value: "female", labelEn: "Female", labelEs: "Femenino", icon: "female" },
      { value: "other", labelEn: "Other", labelEs: "Otro", icon: "user" },
    ],
  },
  {
    id: "demographics_ssn",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 4,
    labelEn: "What is your Social Security Number?",
    labelEs: "¿Cuál es su número de Seguro Social?",
    helperTextEn: "XXX-XX-XXXX or select None",
    helperTextEs: "XXX-XX-XXXX o seleccione Ninguno",
    inputType: "text",
    icon: "shield",
    required: false,
    fieldPath: "demographics.ssn",
    validation: { pattern: /^\d{3}-\d{2}-\d{4}$|^$/ },
  },
  {
    id: "demographics_citizenshipStatus",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 5,
    labelEn: "What is your citizenship status?",
    labelEs: "¿Cuál es su estatus de ciudadanía?",
    inputType: "single_select",
    icon: "globe",
    required: true,
    fieldPath: "demographics.citizenshipStatus",
    options: [
      { value: "us_citizen", labelEn: "US Citizen", labelEs: "Ciudadano de EE.UU.", icon: "flag" },
      { value: "permanent_resident", labelEn: "Permanent Resident", labelEs: "Residente Permanente", icon: "home" },
      { value: "other", labelEn: "Other", labelEs: "Otro", icon: "globe" },
    ],
  },
  {
    id: "demographics_taxId",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 6,
    labelEn: "What is your Tax ID number?",
    labelEs: "¿Cuál es su número de identificación fiscal?",
    helperTextEn: "For ITIN or other tax ID, or select None",
    helperTextEs: "Para ITIN u otro ID fiscal, o seleccione Ninguno",
    inputType: "text",
    icon: "file-text",
    required: false,
    fieldPath: "demographics.taxId",
  },
  {
    id: "demographics_additionalIdType",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 7,
    labelEn: "Do you have another type of ID?",
    labelEs: "¿Tiene otro tipo de identificación?",
    inputType: "single_select",
    icon: "id-card",
    required: false,
    fieldPath: "demographics.additionalIdType",
    options: [
      { value: "drivers_license", labelEn: "Driver's License", labelEs: "Licencia de Conducir", icon: "car" },
      { value: "passport", labelEn: "Passport", labelEs: "Pasaporte", icon: "globe" },
      { value: "state_id", labelEn: "State ID", labelEs: "ID Estatal", icon: "id-card" },
      { value: "none", labelEn: "None", labelEs: "Ninguno", icon: "x" },
    ],
  },
  {
    id: "demographics_additionalIdExpiration",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 8,
    labelEn: "What is the expiration date of your ID?",
    labelEs: "¿Cuál es la fecha de vencimiento de su identificación?",
    helperTextEn: "Month / Day / Year",
    helperTextEs: "Mes / Día / Año",
    inputType: "date",
    icon: "calendar",
    required: false,
    fieldPath: "demographics.additionalIdExpiration",
    conditional: { field: "demographics.additionalIdType", value: ["drivers_license", "passport", "state_id"] },
  },
  {
    id: "demographics_maritalStatus",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 9,
    labelEn: "What is your marital status?",
    labelEs: "¿Cuál es su estado civil?",
    inputType: "single_select",
    icon: "heart",
    required: true,
    fieldPath: "demographics.maritalStatus",
    options: [
      { value: "single", labelEn: "Single", labelEs: "Soltero/a", icon: "user" },
      { value: "married", labelEn: "Married", labelEs: "Casado/a", icon: "heart" },
      { value: "divorced", labelEn: "Divorced", labelEs: "Divorciado/a", icon: "heart-off" },
      { value: "widowed", labelEn: "Widowed", labelEs: "Viudo/a", icon: "heart-off" },
      { value: "separated", labelEn: "Separated", labelEs: "Separado/a", icon: "users" },
    ],
  },
  {
    id: "demographics_legallyMarried",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 10,
    labelEn: "Are you legally married?",
    labelEs: "¿Está legalmente casado/a?",
    inputType: "yes_no",
    icon: "scale",
    required: true,
    fieldPath: "demographics.legallyMarried",
  },
  {
    id: "demographics_race",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 11,
    labelEn: "What is your race?",
    labelEs: "¿Cuál es su raza?",
    inputType: "single_select",
    icon: "users",
    required: true,
    fieldPath: "demographics.race",
    options: [
      { value: "white", labelEn: "White", labelEs: "Blanco/a", icon: "👤" },
      { value: "black", labelEn: "Black or African American", labelEs: "Negro/a o Afroamericano/a", icon: "👤" },
      { value: "asian", labelEn: "Asian", labelEs: "Asiático/a", icon: "👤" },
      { value: "native_american", labelEn: "Native American", labelEs: "Nativo Americano/a", icon: "👤" },
      { value: "pacific_islander", labelEn: "Pacific Islander", labelEs: "Isleño del Pacífico", icon: "👤" },
      { value: "other", labelEn: "Other", labelEs: "Otro", icon: "👤" },
    ],
  },
  {
    id: "demographics_ethnicity",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 12,
    labelEn: "What is your ethnicity?",
    labelEs: "¿Cuál es su etnia?",
    inputType: "single_select",
    icon: "users",
    required: true,
    fieldPath: "demographics.ethnicity",
    options: [
      { value: "hispanic_latino", labelEn: "Hispanic or Latino", labelEs: "Hispano o Latino", icon: "👤" },
      { value: "not_hispanic_latino", labelEn: "Not Hispanic or Latino", labelEs: "No Hispano o Latino", icon: "👤" },
    ],
  },
];

// Address questions (grouped)
const addressQuestions: Question[] = [
  {
    id: "demographics_address_street",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 13,
    labelEn: "What is your street address?",
    labelEs: "¿Cuál es su dirección calle?",
    helperTextEn: "Example: 123 Main Street",
    helperTextEs: "Ejemplo: 123 Calle Principal",
    inputType: "text",
    icon: "home",
    required: true,
    fieldPath: "demographics.residentialAddress.street",
  },
  {
    id: "demographics_address_apt",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 14,
    labelEn: "What is your apartment number?",
    labelEs: "¿Cuál es su número de apartamento?",
    helperTextEn: "Leave blank if no apartment",
    helperTextEs: "Dejar en blanco si no hay apartamento",
    inputType: "text",
    icon: "building",
    required: false,
    fieldPath: "demographics.residentialAddress.apt",
  },
  {
    id: "demographics_address_city",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 15,
    labelEn: "What city do you live in?",
    labelEs: "¿En qué ciudad vive?",
    inputType: "text",
    icon: "map-pin",
    required: true,
    fieldPath: "demographics.residentialAddress.city",
  },
  {
    id: "demographics_address_zip",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 16,
    labelEn: "What is your zip code?",
    labelEs: "¿Cuál es su código postal?",
    helperTextEn: "5 digits",
    helperTextEs: "5 dígitos",
    inputType: "text",
    icon: "map-pin",
    required: true,
    fieldPath: "demographics.residentialAddress.zipCode",
    validation: { pattern: /^\d{5}$/, minLength: 5, maxLength: 5 },
  },
];

// Phone questions
const phoneQuestions: Question[] = [
  {
    id: "demographics_homePhone",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 17,
    labelEn: "What is your home phone number?",
    labelEs: "¿Cuál es su número de teléfono de casa?",
    helperTextEn: "XXX-XXX-XXXX or select No Home Phone",
    helperTextEs: "XXX-XXX-XXXX o seleccione Sin Teléfono de Casa",
    inputType: "phone",
    icon: "phone",
    required: false,
    fieldPath: "demographics.homePhone",
  },
  {
    id: "demographics_cellPhone",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 18,
    labelEn: "What is your cell phone number?",
    labelEs: "¿Cuál es su número de teléfono celular?",
    helperTextEn: "XXX-XXX-XXXX",
    helperTextEs: "XXX-XXX-XXXX",
    inputType: "phone",
    icon: "smartphone",
    required: true,
    fieldPath: "demographics.cellPhone",
  },
  {
    id: "demographics_hasSmartphone",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 19,
    labelEn: "Do you have a smartphone?",
    labelEs: "¿Tiene un teléfono inteligente?",
    inputType: "yes_no",
    icon: "smartphone",
    required: true,
    fieldPath: "demographics.hasSmartphone",
  },
  {
    id: "demographics_textConsent",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 20,
    labelEn: "Can we send you text messages?",
    labelEs: "¿Podemos enviarle mensajes de texto?",
    helperTextEn: "For appointment reminders and updates",
    helperTextEs: "Para recordatorios de citas y actualizaciones",
    inputType: "yes_no",
    icon: "message-square",
    required: true,
    fieldPath: "demographics.textConsent",
  },
];

// Email question
const emailQuestion: Question = {
  id: "demographics_email",
  section: "demographics",
  sectionIndex: 0,
  questionIndex: 21,
  labelEn: "What is your email address?",
  labelEs: "¿Cuál es su dirección de correo electrónico?",
  helperTextEn: "Example: maria@email.com or select None",
  helperTextEs: "Ejemplo: maria@email.com o seleccione Ninguno",
  inputType: "text",
  icon: "mail",
  required: false,
  fieldPath: "demographics.email",
  validation: { pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+|^$/ },
};

// Mailing address
const mailingAddressQuestions: Question[] = [
  {
    id: "demographics_mailingAddressSame",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 22,
    labelEn: "Is your mailing address the same as your home address?",
    labelEs: "¿Es su dirección postal la misma que su dirección de casa?",
    inputType: "yes_no",
    icon: "home",
    required: true,
    fieldPath: "demographics.mailingAddressSame",
  },
  {
    id: "demographics_mailingAddress_street",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 23,
    labelEn: "What is your mailing street address?",
    labelEs: "¿Cuál es su dirección postal calle?",
    inputType: "text",
    icon: "map-pin",
    required: true,
    fieldPath: "demographics.mailingAddress.street",
    conditional: { field: "demographics.mailingAddressSame", value: "no" },
  },
  {
    id: "demographics_mailingAddress_apt",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 24,
    labelEn: "What is your mailing apartment number?",
    labelEs: "¿Cuál es su número de apartamento postal?",
    inputType: "text",
    icon: "building",
    required: false,
    fieldPath: "demographics.mailingAddress.apt",
    conditional: { field: "demographics.mailingAddressSame", value: "no" },
  },
  {
    id: "demographics_mailingAddress_city",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 25,
    labelEn: "What city is your mailing address in?",
    labelEs: "¿En qué ciudad está su dirección postal?",
    inputType: "text",
    icon: "map-pin",
    required: true,
    fieldPath: "demographics.mailingAddress.city",
    conditional: { field: "demographics.mailingAddressSame", value: "no" },
  },
  {
    id: "demographics_mailingAddress_zip",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 26,
    labelEn: "What is your mailing zip code?",
    labelEs: "¿Cuál es su código postal postal?",
    inputType: "text",
    icon: "map-pin",
    required: true,
    fieldPath: "demographics.mailingAddress.zipCode",
    validation: { pattern: /^\d{5}$/, minLength: 5, maxLength: 5 },
    conditional: { field: "demographics.mailingAddressSame", value: "no" },
  },
];

// Emergency contact
const emergencyContactQuestions: Question[] = [
  {
    id: "demographics_emergencyContact_name",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 27,
    labelEn: "Who is your emergency contact?",
    labelEs: "¿Quién es su contacto de emergencia?",
    helperTextEn: "Full name",
    helperTextEs: "Nombre completo",
    inputType: "text",
    icon: "phone",
    required: true,
    fieldPath: "demographics.emergencyContact.name",
  },
  {
    id: "demographics_emergencyContact_relationship",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 28,
    labelEn: "What is your relationship to this person?",
    labelEs: "¿Cuál es su relación con esta persona?",
    helperTextEn: "Example: Spouse, Parent, Friend",
    helperTextEs: "Ejemplo: Esposo/a, Padre/Madre, Amigo/a",
    inputType: "text",
    icon: "users",
    required: true,
    fieldPath: "demographics.emergencyContact.relationship",
  },
  {
    id: "demographics_emergencyContact_phone",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 29,
    labelEn: "What is their phone number?",
    labelEs: "¿Cuál es su número de teléfono?",
    inputType: "phone",
    icon: "phone",
    required: true,
    fieldPath: "demographics.emergencyContact.phone",
  },
];

// Additional demographic questions
const additionalDemographicQuestions: Question[] = [
  {
    id: "demographics_ncResident",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 30,
    labelEn: "Are you a permanent resident of North Carolina?",
    labelEs: "¿Es residente permanente de Carolina del Norte?",
    helperTextEn: "You must live in NC to receive services",
    helperTextEs: "Debe vivir en NC para recibir servicios",
    inputType: "yes_no",
    icon: "map",
    required: true,
    fieldPath: "demographics.ncResident",
  },
  {
    id: "demographics_applicationType",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 31,
    labelEn: "What type of application is this?",
    labelEs: "¿Qué tipo de solicitud es esta?",
    inputType: "single_select",
    icon: "file-text",
    required: true,
    fieldPath: "demographics.applicationType",
    options: [
      { value: "first_time", labelEn: "First Time Patient", labelEs: "Paciente Primera Vez", icon: "user-plus" },
      { value: "renewing", labelEn: "Renewing Patient", labelEs: "Paciente Renovando", icon: "refresh-cw" },
      { value: "former_patient", labelEn: "Former Patient", labelEs: "Paciente Antiguo", icon: "history" },
    ],
  },
  {
    id: "demographics_hasMedicalInsurance",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 32,
    labelEn: "Do you have medical health insurance?",
    labelEs: "¿Tiene seguro médico de salud?",
    inputType: "single_select",
    icon: "shield",
    required: true,
    fieldPath: "demographics.hasMedicalInsurance",
    options: [
      { value: "insured", labelEn: "Yes, I have insurance", labelEs: "Sí, tengo seguro", icon: "check-circle" },
      { value: "uninsured", labelEn: "No, I don't have insurance", labelEs: "No, no tengo seguro", icon: "x-circle" },
      { value: "medicaid", labelEn: "Medicaid", labelEs: "Medicaid", icon: "shield" },
      { value: "medicare", labelEn: "Medicare", labelEs: "Medicare", icon: "shield" },
    ],
  },
  {
    id: "demographics_medicaidId",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 33,
    labelEn: "What is your Medicaid ID?",
    labelEs: "¿Cuál es su ID de Medicaid?",
    inputType: "text",
    icon: "id-card",
    required: false,
    fieldPath: "demographics.medicaidId",
    conditional: { field: "demographics.hasMedicalInsurance", value: ["medicaid"] },
  },
  {
    id: "demographics_appliedForBenefits",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 34,
    labelEn: "Did you apply for Medicaid, Social Security Disability, or Medicare in the last year?",
    labelEs: "¿Solicitó Medicaid, Seguro Social por Discapacidad o Medicare el año pasado?",
    inputType: "yes_no",
    icon: "file-check",
    required: true,
    fieldPath: "demographics.appliedForBenefits",
  },
  {
    id: "demographics_benefitsAppliedFor",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 35,
    labelEn: "Which benefits did you apply for?",
    labelEs: "¿Para qué beneficios solicitó?",
    helperTextEn: "Select all that apply",
    helperTextEs: "Seleccione todos los que apliquen",
    inputType: "multi_select",
    icon: "check-square",
    required: false,
    fieldPath: "demographics.benefitsAppliedFor",
    conditional: { field: "demographics.appliedForBenefits", value: "yes" },
    options: [
      { value: "medicaid", labelEn: "Medicaid", labelEs: "Medicaid", icon: "shield" },
      { value: "ssd", labelEn: "Social Security Disability", labelEs: "Seguro Social por Discapacidad", icon: "shield" },
      { value: "medicare", labelEn: "Medicare", labelEs: "Medicare", icon: "shield" },
      { value: "food_stamps", labelEn: "Food Stamps (SNAP)", labelEs: "Estampillas de Comida (SNAP)", icon: "shopping-cart" },
    ],
  },
  {
    id: "demographics_fullTimeStudent",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 36,
    labelEn: "Are you a full-time student at a 4-year university?",
    labelEs: "¿Es estudiante de tiempo completo en una universidad de 4 años?",
    inputType: "yes_no",
    icon: "graduation-cap",
    required: true,
    fieldPath: "demographics.fullTimeStudent",
  },
  {
    id: "demographics_university",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 37,
    labelEn: "Which university do you attend?",
    labelEs: "¿A qué universidad asiste?",
    inputType: "text",
    icon: "graduation-cap",
    required: false,
    fieldPath: "demographics.university",
    conditional: { field: "demographics.fullTimeStudent", value: "yes" },
  },
  {
    id: "demographics_transportation",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 38,
    labelEn: "How do you usually get around?",
    labelEs: "¿Cómo suele desplazarse?",
    inputType: "single_select",
    icon: "car",
    required: true,
    fieldPath: "demographics.transportation",
    options: [
      { value: "car", labelEn: "Car", labelEs: "Automóvil", icon: "car" },
      { value: "bus", labelEn: "Bus", labelEs: "Autobús", icon: "bus" },
      { value: "walk", labelEn: "Walk", labelEs: "Caminar", icon: "footprints" },
      { value: "ride_share", labelEn: "Ride Share (Uber/Lyft)", labelEs: "Transporte Compartido (Uber/Lyft)", icon: "smartphone" },
      { value: "family_friend", labelEn: "Family or Friend", labelEs: "Familia o Amigo", icon: "users" },
      { value: "other", labelEn: "Other", labelEs: "Otro", icon: "more-horizontal" },
    ],
  },
  {
    id: "demographics_transportationOther",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 39,
    labelEn: "How else do you get around?",
    labelEs: "¿De qué otra manera se desplaza?",
    inputType: "text",
    icon: "more-horizontal",
    required: false,
    fieldPath: "demographics.transportationOther",
    conditional: { field: "demographics.transportation", value: "other" },
  },
  {
    id: "demographics_currentlyPregnant",
    section: "demographics",
    sectionIndex: 0,
    questionIndex: 40,
    labelEn: "Are you currently pregnant?",
    labelEs: "¿Está actualmente embarazada?",
    inputType: "yes_no",
    icon: "baby",
    required: true,
    fieldPath: "demographics.currentlyPregnant",
  },
];

// Combine all Section 1 questions
const section1AllQuestions = [
  ...section1Questions,
  ...addressQuestions,
  ...phoneQuestions,
  emailQuestion,
  ...mailingAddressQuestions,
  ...emergencyContactQuestions,
  ...additionalDemographicQuestions,
];

// Update question indices after combining
section1AllQuestions.forEach((q, i) => (q.questionIndex = i));

// ============================================================================
// Section 2: Additional Patient Questions (Page 2) - ~12 questions
// ============================================================================

const section2Questions: Question[] = [
  {
    id: "additionalQuestions_seenByPcpLastYear",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 0,
    labelEn: "Have you been seen by a primary care provider in the last year?",
    labelEs: "¿Ha sido atendido/a por un proveedor de atención primaria en el último año?",
    inputType: "yes_no",
    icon: "stethoscope",
    required: true,
    fieldPath: "additionalQuestions.seenByPcpLastYear",
  },
  {
    id: "additionalQuestions_pcpWhere",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 1,
    labelEn: "Where did you see them?",
    labelEs: "¿Dónde lo/a vio?",
    inputType: "text",
    icon: "map-pin",
    required: false,
    fieldPath: "additionalQuestions.pcpWhere",
    conditional: { field: "additionalQuestions.seenByPcpLastYear", value: "yes" },
  },
  {
    id: "additionalQuestions_pcpWhen",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 2,
    labelEn: "When was your last visit?",
    labelEs: "¿Cuándo fue su última visita?",
    inputType: "text",
    icon: "calendar",
    required: false,
    fieldPath: "additionalQuestions.pcpWhen",
    conditional: { field: "additionalQuestions.seenByPcpLastYear", value: "yes" },
  },
  {
    id: "additionalQuestions_pcpWhyStopped",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 3,
    labelEn: "Why did you stop seeing them?",
    labelEs: "¿Por qué dejó de verlo/a?",
    inputType: "text",
    icon: "help-circle",
    required: false,
    fieldPath: "additionalQuestions.pcpWhyStopped",
  },
  {
    id: "additionalQuestions_pcpFutureAppts",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 4,
    labelEn: "Do you have future appointments scheduled?",
    labelEs: "¿Tiene citas futuras programadas?",
    inputType: "yes_no",
    icon: "calendar",
    required: false,
    fieldPath: "additionalQuestions.pcpFutureAppts",
    conditional: { field: "additionalQuestions.seenByPcpLastYear", value: "yes" },
  },
  {
    id: "additionalQuestions_seenAtWakeMed",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 5,
    labelEn: "Have you been seen at Wake Med in the last year?",
    labelEs: "¿Ha sido atendido/a en Wake Med en el último año?",
    inputType: "yes_no",
    icon: "hospital",
    required: true,
    fieldPath: "additionalQuestions.seenAtWakeMed",
  },
  {
    id: "additionalQuestions_wakeMedWhen",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 6,
    labelEn: "When were you at Wake Med?",
    labelEs: "¿Cuándo estuvo en Wake Med?",
    inputType: "text",
    icon: "calendar",
    required: false,
    fieldPath: "additionalQuestions.wakeMedWhen",
    conditional: { field: "additionalQuestions.seenAtWakeMed", value: "yes" },
  },
  {
    id: "additionalQuestions_wakeMedWhat",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 7,
    labelEn: "What did you go to Wake Med for?",
    labelEs: "¿Para qué fue a Wake Med?",
    inputType: "text",
    icon: "help-circle",
    required: false,
    fieldPath: "additionalQuestions.wakeMedWhat",
    conditional: { field: "additionalQuestions.seenAtWakeMed", value: "yes" },
  },
  {
    id: "additionalQuestions_seenAtUNC",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 8,
    labelEn: "Have you been seen at UNC in the last year?",
    labelEs: "¿Ha sido atendido/a en UNC en el último año?",
    inputType: "yes_no",
    icon: "hospital",
    required: true,
    fieldPath: "additionalQuestions.seenAtUNC",
  },
  {
    id: "additionalQuestions_uncWhen",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 9,
    labelEn: "When were you at UNC?",
    labelEs: "¿Cuándo estuvo en UNC?",
    inputType: "text",
    icon: "calendar",
    required: false,
    fieldPath: "additionalQuestions.uncWhen",
    conditional: { field: "additionalQuestions.seenAtUNC", value: "yes" },
  },
  {
    id: "additionalQuestions_uncWhat",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 10,
    labelEn: "What did you go to UNC for?",
    labelEs: "¿Para qué fue a UNC?",
    inputType: "text",
    icon: "help-circle",
    required: false,
    fieldPath: "additionalQuestions.uncWhat",
    conditional: { field: "additionalQuestions.seenAtUNC", value: "yes" },
  },
  {
    id: "additionalQuestions_seenAtDuke",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 11,
    labelEn: "Have you been seen at Duke in the last year?",
    labelEs: "¿Ha sido atendido/a en Duke en el último año?",
    inputType: "yes_no",
    icon: "hospital",
    required: true,
    fieldPath: "additionalQuestions.seenAtDuke",
  },
  {
    id: "additionalQuestions_dukeWhen",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 12,
    labelEn: "When were you at Duke?",
    labelEs: "¿Cuándo estuvo en Duke?",
    inputType: "text",
    icon: "calendar",
    required: false,
    fieldPath: "additionalQuestions.dukeWhen",
    conditional: { field: "additionalQuestions.seenAtDuke", value: "yes" },
  },
  {
    id: "additionalQuestions_dukeWhat",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 13,
    labelEn: "What did you go to Duke for?",
    labelEs: "¿Para qué fue a Duke?",
    inputType: "text",
    icon: "help-circle",
    required: false,
    fieldPath: "additionalQuestions.dukeWhat",
    conditional: { field: "additionalQuestions.seenAtDuke", value: "yes" },
  },
  {
    id: "additionalQuestions_pcpPolicyAcknowledged",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 14,
    labelEn: "I understand that I need a primary care provider to receive ongoing care at Urban Ministries.",
    labelEs: "Entiendo que necesito un proveedor de atención primaria para recibir atención continua en Urban Ministries.",
    helperTextEn: "Tap the checkbox to acknowledge",
    helperTextEs: "Toque la casilla para reconocer",
    inputType: "checkbox",
    icon: "check-circle",
    required: true,
    fieldPath: "additionalQuestions.pcpPolicyAcknowledged",
  },
  {
    id: "additionalQuestions_educationLevel",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 15,
    labelEn: "What is the highest level of education you have completed?",
    labelEs: "¿Cuál es el nivel más alto de educación que ha completado?",
    inputType: "single_select",
    icon: "graduation-cap",
    required: true,
    fieldPath: "additionalQuestions.educationLevel",
    options: [
      { value: "less_than_high_school", labelEn: "Less than high school", labelEs: "Menos que secundaria", icon: "book" },
      { value: "high_school", labelEn: "High school or GED", labelEs: "Secundaria o GED", icon: "graduation-cap" },
      { value: "some_college", labelEn: "Some college", labelEs: "Alguna universidad", icon: "book-open" },
      { value: "college_degree", labelEn: "College degree", labelEs: "Título universitario", icon: "award" },
      { value: "graduate_degree", labelEn: "Graduate degree", labelEs: "Título de posgrado", icon: "award" },
    ],
  },
  {
    id: "additionalQuestions_internetAccess",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 16,
    labelEn: "Do you have access to the internet at home?",
    labelEs: "¿Tiene acceso a internet en casa?",
    inputType: "yes_no",
    icon: "wifi",
    required: true,
    fieldPath: "additionalQuestions.internetAccess",
  },
  {
    id: "additionalQuestions_printerAccess",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 17,
    labelEn: "Do you have access to a printer?",
    labelEs: "¿Tiene acceso a una impresora?",
    inputType: "yes_no",
    icon: "printer",
    required: true,
    fieldPath: "additionalQuestions.printerAccess",
  },
  {
    id: "additionalQuestions_emailAtcLetter",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 18,
    labelEn: "Is it okay to email your ATC letter to you?",
    labelEs: "¿Está bien enviarle su carta ATC por correo electrónico?",
    helperTextEn: "Your letter from Urban Ministries",
    helperTextEs: "Su carta de Urban Ministries",
    inputType: "yes_no",
    icon: "mail",
    required: true,
    fieldPath: "additionalQuestions.emailAtcLetter",
  },
  {
    id: "additionalQuestions_telehealthCapable",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 19,
    labelEn: "Are you able to do video calls for telehealth appointments?",
    labelEs: "¿Puede hacer videollamadas para citas de telemedicina?",
    inputType: "yes_no",
    icon: "video",
    required: true,
    fieldPath: "additionalQuestions.telehealthCapable",
  },
  {
    id: "additionalQuestions_readLanguage",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 20,
    labelEn: "What language do you prefer to read?",
    labelEs: "¿Qué idioma prefiere leer?",
    inputType: "text",
    icon: "book",
    required: true,
    fieldPath: "additionalQuestions.readLanguage",
  },
  {
    id: "additionalQuestions_readUnable",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 21,
    labelEn: "Are you unable to read?",
    labelEs: "¿Es incapaz de leer?",
    inputType: "yes_no",
    icon: "book-off",
    required: true,
    fieldPath: "additionalQuestions.readUnable",
  },
  {
    id: "additionalQuestions_writeLanguage",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 22,
    labelEn: "What language do you prefer to write?",
    labelEs: "¿Qué idioma prefiere escribir?",
    inputType: "text",
    icon: "pen-tool",
    required: true,
    fieldPath: "additionalQuestions.writeLanguage",
  },
  {
    id: "additionalQuestions_writeUnable",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 23,
    labelEn: "Are you unable to write?",
    labelEs: "¿Es incapaz de escribir?",
    inputType: "yes_no",
    icon: "pen-off",
    required: true,
    fieldPath: "additionalQuestions.writeUnable",
  },
  {
    id: "additionalQuestions_speakLanguage",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 24,
    labelEn: "What language do you prefer to speak?",
    labelEs: "¿Qué idioma prefiere hablar?",
    inputType: "text",
    icon: "message-square",
    required: true,
    fieldPath: "additionalQuestions.speakLanguage",
  },
  {
    id: "additionalQuestions_interpreterNeeded",
    section: "additionalQuestions",
    sectionIndex: 1,
    questionIndex: 25,
    labelEn: "Do you need an interpreter?",
    labelEs: "¿Necesita un intérprete?",
    inputType: "yes_no",
    icon: "languages",
    required: true,
    fieldPath: "additionalQuestions.interpreterNeeded",
  },
];

// ============================================================================
// Export all sections
// ============================================================================

export const sections: Section[] = [
  {
    id: "demographics",
    titleEn: "Patient Information",
    titleEs: "Información del Paciente",
    descriptionEn: "Please tell us about yourself",
    descriptionEs: "Por favor, cuéntenos sobre usted",
    questions: section1AllQuestions,
  },
  {
    id: "additionalQuestions",
    titleEn: "Additional Questions",
    titleEs: "Preguntas Adicionales",
    descriptionEn: "Healthcare and communication information",
    descriptionEs: "Información de atención médica y comunicación",
    questions: section2Questions,
  },
];

export const getAllQuestions = (): Question[] => {
  return sections.flatMap((section) => section.questions);
};

export const getSectionById = (id: string): Section | undefined => {
  return sections.find((s) => s.id === id);
};

export const getQuestionById = (id: string): Question | undefined => {
  return getAllQuestions().find((q) => q.id === id);
};
